### ISSUE TITLE
File BrightMigrationOld.json 404 (Not Found)

### ISSUE THREAD

**Issue by vmunozre** [TribalyteTechnologies/BrightByte#1]
Hi Tribalyte Technologies,

When I try to migrate an account to do login I recibe:

`GET http://localhost:8100/assets/build/BrightMigrationOld.json 404 (Not Found)`

I debbug the code and localized the error. It's in line 433 from file `contract-manager.service.ts` at the function `initMigrationOld`.

I first instance i thinked that the contract "BrightMigrationOld" didn't migrated to the network correctly. But this contract don't exist. And I don't find `BrightMigrationOld.json` in any folder.

Can you help me to found this file and fix the error?
Thanks!

**Comment by eelopez** [comment]
Hi Victor,

The migration was only necessary if you were using an old version of BrightByte (v0.1.x), where the `BrightMigrationOld.json` contains all the information of the old Smart Contracts.

Soon there will be a release of BrightByte, where we will remove the migration, but if you want to use it now without the migration, you can check this commit with the latest changes: [Solved Front-End issues](https://github.com/TribalyteTechnologies/BrightByte/tree/5bcdc7dbffa027ad70a1842f8442f1ea5db3f612). Remember that is a developer branch.

**Comment by rbarriuso** [comment]
Hi @vmunozre. We just released v0.2.1, which removes the migration logic. Please have a look to https://github.com/TribalyteTechnologies/BrightByte/releases/tag/v0.2.1
