### ISSUE TITLE
BitBucket provider in Batch Upload modal not working properly

### ISSUE THREAD

**Issue by maguirre-tribalyte** [TribalyteTechnologies/BrightByte#41]
When I, a new user of BrightByte, try to make my first batch upload, the page redirects me to github for authentication. I do not have a Github account, so I close the pop-up, and no more actions are allowed in the Batch Upload Modal.

When I finally created a Github account, and authenticated myself, a popup appears with the BitBucket authentication mechanism, and I can after this import the commits as a batch.

What would have been expected is the possibility to authenticate via BitBucket without having to authenticate via Github first

**Comment by rbarriuso** [comment]
@maguirre-tribalyte The batch upload feature should work regardless of the Bitbucket workspaces or the GitHub organizations configured and whether you have a GitHub account or not. We've improved this process in v0.8.8. Let me know if you still have any trouble
